#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.redis.entities
server:
  port: 8080
spring:
  application:
    name: redis-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      test-while-idle: false
#    password: 123456
#    url: jdbc:mysql://localhost:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#  rabbitmq:
#    host: 127.0.0.1
#    password: guest
#    port: 5672
#    username: guest
#    virtual-host: /
  redis:
#    database: 0
    host: 192.168.92.128
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
#    password: ''
#    port: 6379
